In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.3'

# Python List 的特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [6]:
L[5] = 'machine learning'

In [7]:
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

In [8]:
# 因此，python list非常灵活，但是耗时较多


In [9]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 定义限定类型的array，i为整型，但并没有将其视为向量或者矩阵对象


# numpy.array

In [13]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
nparr.dtype

dtype('int32')

In [15]:
nparr[5] = 5.0

In [16]:
nparr
nparr.dtype              #转换类型不起作用

dtype('int32')

In [18]:
nparr2 = np.array([1,2,3.0])

In [19]:
nparr2

array([1., 2., 3.])

In [21]:
nparr2.dtype

dtype('float64')

# 其他创建numpy.array的方法

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros(shape = (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [30]:
np.full((3,5), 666.0)             #shape = (3,5), fill_value = 666

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

# arange

In [31]:
[i for i in range(0, 20 ,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

# linspace

In [34]:
np.linspace(0, 20, 10)        # 在0和20 之间进行10等分，包含始终点

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [35]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

# numpy.random

In [36]:
np.random.randint(10)

9

In [38]:
np.random.randint(0,10)

5

In [39]:
np.random.randint(0,10,10)        #前闭后开的数组

array([9, 6, 4, 4, 8, 9, 3, 6, 9, 6])

In [40]:
np.random.randint(0, 10, size = (3,5))

array([[6, 4, 1, 2, 0],
       [3, 0, 9, 3, 6],
       [1, 8, 0, 7, 1]])

In [41]:
np.random.seed(66)

In [42]:
np.random.randint(0, 10, size = (3,5))


array([[4, 7, 3, 5, 3],
       [0, 7, 6, 0, 2],
       [2, 2, 6, 0, 8]])

In [44]:
np.random.seed(66)                #显式地指定随机种子
np.random.randint(0, 10, size = (3,5))

array([[4, 7, 3, 5, 3],
       [0, 7, 6, 0, 2],
       [2, 2, 6, 0, 8]])

In [45]:
np.random.random()        #0,1之间的随机浮点数

0.21546800091196194

In [46]:
np.random.random((3,5)) 

array([[0.91546757, 0.89115938, 0.11505204, 0.04503268, 0.54182627],
       [0.72553119, 0.21095236, 0.49666906, 0.7686794 , 0.28740058],
       [0.0507242 , 0.50286467, 0.08729047, 0.02777163, 0.30854294]])

In [47]:
np.random.normal()

-2.0342905462891103

In [48]:
np.random.normal(10, 100,size = (3,5))         #指定均值为10 ，方差为100， size为（3，5），正太分布的数组

array([[ -12.27192517,  -53.05230074, -150.3639109 ,  207.36857583,
         -60.72424821],
       [ -15.9382171 ,  229.44314599,  -59.4674387 , -115.52797309,
        -153.67364454],
       [  83.1394082 , -194.14507791,  112.01649823,  179.71757842,
         -43.91260517]])

In [49]:
help(np.random.randint)        #randint?同

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i