# numpy 的矩阵运算

In [8]:
n = 10000000
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
%%time
A = []
for e in L:
    A.append((2*e))

Wall time: 2.1 s


In [10]:
%%time
A = [2 * e for e in L]

Wall time: 1.29 s
Compiler : 160 ms


In [11]:
import numpy as np

In [12]:
L = np.arange(n)

In [15]:
%%time
A = np.array(2*e for e in L)

Wall time: 170 ms


In [16]:
%%time
A = L*2

Wall time: 30 ms


In [17]:
A

array([       0,        2,        4, ..., 19999994, 19999996, 19999998])

# Universal Function

In [18]:
# 矩阵的四则运算均支持

# 矩阵之间的运算

In [19]:
A = np.arange(4).reshape((2,2))
B = np.full((2,2),10)

In [20]:
A

array([[0, 1],
       [2, 3]])

In [21]:
B

array([[10, 10],
       [10, 10]])

In [22]:
A + B

array([[10, 11],
       [12, 13]])

In [23]:
A * B             # 对应项相乘，点乘

array([[ 0, 10],
       [20, 30]])

In [24]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [25]:
A.dot(B)          # 矩阵乘法

array([[10, 10],
       [50, 50]])

In [26]:
A.T         # 矩阵转置

array([[0, 2],
       [1, 3]])

# 向量和矩阵之间运算

In [27]:
v = np.array([1,2])

In [28]:
v + A              # 广播原则

array([[1, 3],
       [3, 5]])

In [30]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [31]:
np.tile(v, (2,1))           # tile 堆叠，在行方向2次，在列方向1次

array([[1, 2],
       [1, 2]])

In [32]:
v * A

array([[0, 2],
       [2, 6]])

In [33]:
v.dot(A)

array([4, 7])

In [34]:
A.dot(v)             # v 被当成一个列向量

array([2, 8])

# 矩阵的逆

In [35]:
A 

array([[0, 1],
       [2, 3]])

In [36]:
np.linalg.inv(A)          #  求逆

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [37]:
X = np.arange(16).reshape(2,8)          # 求解非方阵 的伪逆矩阵
np.linalg.pinv(X)

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])