# 聚合操作
  多个值得到一个值

In [2]:
import numpy as np

In [3]:
L = np.random.random(100)

In [4]:
sum(L)

49.073172243146956

In [5]:
np.sum(L)

49.073172243146956

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)                   # np.sum 效率极高

156 ms ± 165 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.17 ms ± 2.02 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(L)

0.0206096091713851

In [8]:
np.max(L)

0.9986336069542844

In [9]:
L.sum()

49.073172243146956

In [10]:
# min, max, 
# 推荐np.max 方式

In [11]:
x = np.arange(16).reshape(4, -1)

In [12]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(x)

120

In [14]:
np.sum(x, axis = 0)    # 沿列相加，压缩行

array([24, 28, 32, 36])

In [15]:
np.sum(x, axis = 1)        # 沿行相加，压缩列

array([ 6, 22, 38, 54])

In [17]:
np.prod(x+1)         #所有相乘

2004189184

In [18]:
np.mean(x)

7.5

In [19]:
np.median(x)

7.5

In [20]:
np.percentile(big_array, q = 50)          # 分位数

0.49942239505207314

In [21]:
for percent in [0, 25,50 ,75, 100]:
    print(np.percentile(big_array, q = percent))

8.007065321891105e-08
0.24921127458059594
0.49942239505207314
0.7501482368870904
0.9999984869486402


In [22]:
np.var(big_array)   # 方差

0.08348654218559023

In [23]:
np.std(big_array)        # 标准差

0.28894037825404434

In [25]:
x = np.random.normal(0, 1, size = 1000000)

In [26]:
np.mean(x)

0.00030328027612944733

In [27]:
np.std(x)

1.000331457222306

In [28]:
np.percentile(x, q = 50 )

-0.001289724024922517

In [29]:
np.median(x)

-0.001289724024922517