# 索引

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size = 1000000)

In [3]:
np.min(x)

-4.7120449986020105

In [4]:
np.max(x)

4.780412206360725

In [5]:
np.argmin(x)            # 最小值的索引

351157

In [7]:
np.argmax(x)

613773

# 排序和索引

In [8]:
x = np.arange(16)

In [9]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)                   # shuffle 乱序列表
x

array([ 1, 11,  0, 15,  5,  4,  3,  2,  9, 14, 10,  8, 13, 12,  6,  7])

In [13]:
np.sort(x)          # np . 与直接 x.sort 不同

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x

array([ 1, 11,  0, 15,  5,  4,  3,  2,  9, 14, 10,  8, 13, 12,  6,  7])

In [15]:
x.sort()

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
y = np.random.randint(16, size = (4,4))
y

array([[ 5,  8, 10, 14],
       [13, 15, 15, 11],
       [ 1, 14,  9,  2],
       [ 6, 13,  6,  8]])

In [27]:
np.sort(y)

array([[ 5,  8, 10, 14],
       [11, 13, 15, 15],
       [ 1,  2,  9, 14],
       [ 6,  6,  8, 13]])

In [28]:
y

array([[ 5,  8, 10, 14],
       [13, 15, 15, 11],
       [ 1, 14,  9,  2],
       [ 6, 13,  6,  8]])

In [29]:
np.sort(y, axis = 1)

array([[ 5,  8, 10, 14],
       [11, 13, 15, 15],
       [ 1,  2,  9, 14],
       [ 6,  6,  8, 13]])

In [30]:
np.sort(y, axis = 0)

array([[ 1,  8,  6,  2],
       [ 5, 13,  9,  8],
       [ 6, 14, 10, 11],
       [13, 15, 15, 14]])

In [31]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
np.random.shuffle(x)

In [33]:
x

array([ 3,  5, 11, 14,  8,  7,  1, 12,  4, 15,  2,  0, 13,  9,  6, 10])

In [34]:
np.argsort(x)             # 排序的索引位置

array([11,  6, 10,  0,  8,  1, 14,  5,  4, 13, 15,  2,  7, 12,  3,  9],
      dtype=int64)

In [35]:
np.partition(x, 3)            # 3分位， 前后无排序

array([ 1,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 13, 14, 11, 12])

In [36]:
np.argpartition(x, 3)

array([ 6, 11, 10,  0,  8,  1, 14,  5,  4, 13, 15,  9, 12,  3,  2,  7],
      dtype=int64)

In [37]:
y

array([[ 5,  8, 10, 14],
       [13, 15, 15, 11],
       [ 1, 14,  9,  2],
       [ 6, 13,  6,  8]])

In [38]:
np.argsort(y, axis = 1)

array([[0, 1, 2, 3],
       [3, 0, 1, 2],
       [0, 3, 2, 1],
       [0, 2, 3, 1]], dtype=int64)