# numpy.array的基本操作

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# numpy数组的基本属性

In [4]:
x.ndim

1

In [5]:
X.ndim #维度

2

In [6]:
x.shape

(10,)

In [7]:
X.shape

(3, 5)

In [8]:
x.size

10

In [9]:
X.size

15

# 数据访问

In [10]:
x[0]
x[-1]

9

In [11]:
X[0][2]

2

In [12]:
X[(0, 2)]

2

In [13]:
X[2,2]

12

In [14]:
x[0:5]

array([0, 1, 2, 3, 4])

In [15]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [16]:
X[:, 0]

array([ 0,  5, 10])

In [17]:
subX = X[:2,:3]

In [18]:
subX[0,0] = 100.0

In [19]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [20]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [21]:
# 切片会影响原矩阵

In [22]:
subXX = X[:2, :3].copy()
subXX                             #通过copy（）创建副本，不影响原矩阵

array([[100,   1,   2],
       [  5,   6,   7]])

# reshape

In [23]:
x.shape

(10,)

In [26]:
y = x.reshape(2,5)

In [27]:
y.ndim

2

In [28]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
x.reshape(10, -1)  #自动计算另一参数

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [31]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# 合并操作

In [32]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [33]:
x

array([1, 2, 3])

In [34]:
y

array([3, 2, 1])

In [35]:
z = np.concatenate([x, y])
z

array([1, 2, 3, 3, 2, 1])

In [36]:
z.reshape(2, -1)

array([[1, 2, 3],
       [3, 2, 1]])

In [37]:
a = np.array([[1,2,3],[4, 5, 6]])
np.concatenate([a, a])                           #行合并

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([a, a], axis = 1)               #沿列进行合并

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
np.concatenate([a, x.reshape(1, -1)])            # x原来是一个向量，通过reshape形成一个一维数组

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [43]:
 np.vstack([a, x])                   # vstack可以直接合并

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [44]:
b = np.full((2,2), 100)
b

array([[100, 100],
       [100, 100]])

In [46]:
np.hstack([a, b ])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

# 分割操作

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.split(x, [3, 7])        # 指定 数组和分割点，在第几个之后切割 [0,3), [3, 7),[7,10)

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [50]:
x1, x2 = np.split(x, [5])               # 一个参数， 分为两段
x1

array([0, 1, 2, 3, 4])

In [51]:
x2

array([5, 6, 7, 8, 9])

In [52]:
x3, x4 = np.split(x, [3]) 

In [53]:
x3

array([0, 1, 2])

In [54]:
 A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
A1 , A2 = np.split(A, [2])          # 二维数组的分割

In [56]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [57]:
A3 , A4 = np.split(A, [2], axis = 1)      # 二维数组的分割，在列方向
A3 

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [58]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# concatenate  
    ### vstack  ,   hstack
    
# split
    ### vsplit ,   hsplit